version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend
