import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <header className='h-14 bg-neutral-900 border-b border-neutral-700 text-white flex items-center px-4 md:px-6'>
          <Link
            href='/'
            className='text-lg font-semibold tracking-wide hover:text-neutral-200 transition-colors'
          >
            XDrop
          </Link>
        </header>
        <main className='flex-1 min-h-0'>{children}</main>
      </body>
    </html>
  );
}
