server {
    listen 80;
    server_name xdrop.med-000.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name xdrop.med-000.com;

    ssl_certificate /etc/letsencrypt/live/xdrop.med-000.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xdrop.med-000.com/privkey.pem;


    location /api/ {
        proxy_pass http://backend:8080/;
    }

    location /ws/ {
        proxy_pass http://backend:8080/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass http://frontend:3000/;
    }
}